### ISSUE TITLE
Didn't work with crunch generator.|

### ISSUE THREAD

**Issue by jtelo88** [BoboTiG/cracker-ng#3]
Hi Dev,

First of all thanks for this tool, was looking for this long time ago.

Right now Im testing your tool but have problem using crunch with it, This is the line I run:

./cptcracker-ng -f testfile.cpt - crunch 1 4 -f charset.txt mixalpha-numeric

The app show this in screen:

 ~ CPT Cracker-ng v2015.02-03 { Tiger-222 } ~
 - File......: testfile.cpt
 - Generator.: STDIN
 . Working at 0K pwd/sec [0M tries]

 but tries and pwd/sec never change.

Im running it on ubuntu server 14.04 and latest version downloaded from github,

Thanks!

**Comment by BoboTiG** [comment]
Hello Joan,

The right command is:
    crunch 1 4 -f charset.txt mixalpha-numeric | ./cptcracker-ng -f testfile.cpt -

I saw the README file is not well displayed, fixed now :)

**Comment by jtelo88** [comment]
Hi BogoTiG,

Thanks for quick reply and fix it.

Happy new year!
